const feeds = [
    {
        id:0,
        name:"Rabindra Rauta",
        about:" Odisha , 15mnt ago",
        log:"images/profile2.jpg",
        photo:"images/feed1.jpg",
        like1:"images/clarisse-meyer-HoYIncR3AQ8-unsplash.jpg",
        like2:"images/melissa-askew-tSlvoSZK77c-unsplash.jpg",
        like3:"images/sam-manns-p0ZvBVpW3KY-unsplash.jpg",
        likedby:"Suri Bheema Raju",
        totollikes:"2,323",
    },
    {
        id:1,
        name:"Sagar Senapati",
        about:" kolkata , 18mnt ago",
        log:"images/profile4.jpg",
        photo:"images/feed2.jpg",
        like1:"images/clarisse-meyer-HoYIncR3AQ8-unsplash.jpg",
        like2:"images/melissa-askew-tSlvoSZK77c-unsplash.jpg",
        like3:"images/sam-manns-p0ZvBVpW3KY-unsplash.jpg",
        likedby:"Nibedita senapati",
        totollikes:"2,470",
    },
    {
        id:2,
        name:"Papindra Nahak",
        about:" Surat , 25mnt ago",
        log:"images/profile5.jpg",
        photo:"images/feed3.jpg",
        like1:"images/clarisse-meyer-HoYIncR3AQ8-unsplash.jpg",
        like2:"images/melissa-askew-tSlvoSZK77c-unsplash.jpg",
        like3:"images/sam-manns-p0ZvBVpW3KY-unsplash.jpg",
        likedby:"Pratik Reddy",
        totollikes:"2,958",
    },
    {
        id:3,
        name:"Nibedita Senapati",
        about:" BBSR , 10mnt ago",
        log:"images/profile1.jpg",
        photo:"images/feed4.jpg",
        like1:"images/clarisse-meyer-HoYIncR3AQ8-unsplash.jpg",
        like2:"images/melissa-askew-tSlvoSZK77c-unsplash.jpg",
        like3:"images/sam-manns-p0ZvBVpW3KY-unsplash.jpg",
        likedby:"Sagar Senapati",
        totollikes:"2,452",
    },
    {
        id:4,
        name:"Shantanu Senapati",
        about:" dubai , 18mnt ago",
        log:"images/profile6.jpg",
        photo:"images/feed5.jpg",
        like1:"images/clarisse-meyer-HoYIncR3AQ8-unsplash.jpg",
        like2:"images/melissa-askew-tSlvoSZK77c-unsplash.jpg",
        like3:"images/sam-manns-p0ZvBVpW3KY-unsplash.jpg",
        likedby:"Nibedita senapati",
        totollikes:"2,124",
    },
    {
        id:5,
        name:"Arunav Sutar",
        about:" Bangalore , 40mnt ago",
        log:"images/profile7.jpg",
        photo:"images/feed6.jpg",
        like1:"images/clarisse-meyer-HoYIncR3AQ8-unsplash.jpg",
        like2:"images/melissa-askew-tSlvoSZK77c-unsplash.jpg",
        like3:"images/sam-manns-p0ZvBVpW3KY-unsplash.jpg",
        likedby:"Rabindra Rauta",
        totollikes:"2,020",
    }
]